name: Brume
markdown: redcarpet
pygments: true
paginate: 10
permalink: /:title

redcarpet:
  extensions: [strikethrough]

author:
description:

url:

links:
  - url: /
    title: Home
  - url: /about
    title: About
  - url: /archive
    title: Archive
