name: Brume
markdown: redcarpet
pygments: true
paginate: 10
permalink: /:title

redcarpet:
  extensions: [strikethrough]

author:
description:

links:
  - url: /
    name: Home
    title: Home
  - url: /about
    name: About
    title: About
  - url: /archive
    name: Archive
    title: Archive
