plugins:
  - jekyll-last-modified-at
exclude:
  - node_modules
  - src
  - scripts
  - _site
  - dist
  - package.json
  - package-lock.json
  - webpack.config.js
  - TODOLIST.md
include:
  - _posts
  - _drafts
  - api
  - CNAME
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
